"use strict";

// test/sdk.contract.test.js — the API-CONTRACT (semver / ABI) guard for the public SDK surface (T-57.2).
//
// WHY THIS EXISTS
//   index.js is the package's stability contract (T-57.1): a downstream program `require`s it and then
//   integrates against the ACTUAL call/return contract — it calls `buildSeal(entries)` with a fixed
//   arity, reads back a result it destructures for `verdict`, hard-codes the seal `KIND` tag, and
//   branches on the `SCHEMA_VERSION` number. A thin re-export makes it trivial to *silently* break any
//   of that: add a stray key, drop one, rename a namespace member, grow a function's arity, bump a schema
//   version, or drop the `verdict` result key. This suite is the failing thing that stops all of those.
//
//   Crucially it pins the ABI a consumer REALLY depends on, not just symbol names:
//     • functions      -> name : function/<arity>            (parameter count is part of the contract)
//     • frozen consts  -> name : <kind>=<canonicalValue>     (the WIRE VALUE — KIND tag / schema #)
//     • verifySeal      -> its RESULT KEY SET                 (the object shape a consumer destructures)
//   A renamed export is loud; a `SEAL_SCHEMA_VERSION` bumped 1→2, a second required arg on `buildSeal`,
//   or a `verifySeal` that stops returning `verdict` are the SILENT breaks a name-only guard misses —
//   and this guard catches every one.
//
//   Three mutually-reinforcing checks over ONE canonical serialization of the live surface:
//     (A) SEMVER PIN     — the live surface must byte-match a frozen EXPECTED descriptor in THIS file.
//     (B) DOC/CODE DRIFT — docs/SDK.md must carry that SAME canonical block verbatim, and document every
//                          symbol + the semver policy, so the doc cannot silently rot away from code.
//     (C) SINGLE SOURCE  — the descriptor is GENERATED by scripts/gen-sdk-surface.cjs (one command:
//                          `npm run sdk:surface -- --write`), and its `--check` mode is the CI drift gate.
//                          The test proves the generator, the pin, and the doc all agree.
//
//   The detector is proven NON-TRIVIAL: we feed it surfaces with one extra / renamed / removed / retyped
//   key, a GROWN function arity, a BUMPED schema version, and a DROPPED verifySeal result key, and assert
//   the equality check WOULD FAIL for each — i.e. the guard actually catches drift, it isn't a tautology.
//
// PURE / OFFLINE — no chain, no fixtures, no key, no network. Introduces NO new product mechanism.

const { expect } = require("chai");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const api = require("../index.js");

// The generator is the SINGLE SOURCE OF TRUTH for the descriptor format. The test does not re-implement
// serialization; it consumes the generator so the pin, the doc block, and the emitted descriptor can
// never disagree about what "the surface" is.
const gen = require("../scripts/gen-sdk-surface.cjs");
const { kindOf, abiOf, serializeSurface } = gen;

// ---------------------------------------------------------------------------
// (A) THE SEMVER / ABI PIN — the frozen EXPECTED surface. Changing this list is the deliberate, reviewable
//     act of changing the package's public API. If you add/remove/rename a symbol, change an arity, or
//     change a frozen wire value in index.js you MUST update BOTH this pin AND docs/SDK.md — regenerate
//     with `npm run sdk:surface -- --write`, then paste the new block here. The (B)/(C) checks keep the
//     pin, the doc, and the live exports in lockstep.
// ---------------------------------------------------------------------------
const EXPECTED_SURFACE = [
  "PacketSealError : function/1",
  "apiVersion : string",
  "buildAnchorReceipt : function/1",
  "buildReceipt : function/1",
  "buildSeal : function/1",
  "buildTree : function/1",
  "diffManifest : function/2",
  "hashBytes : function/1",
  "hashDir : function/1",
  "hashEntries : function/1",
  "hashFile : function/1",
  "hashPath : function/1",
  "hashing : namespace",
  "hashing.buildTree : function/1",
  "hashing.hashBytes : function/1",
  "hashing.hashDir : function/1",
  "hashing.hashEntries : function/1",
  "hashing.hashFile : function/1",
  "hashing.hashPath : function/1",
  "readReceipt : function/1",
  "readSeal : function/1",
  "receipts : namespace",
  "receipts.ANCHOR_RECEIPT_KIND : string=\"verifyhash.anchor-receipt\"",
  "receipts.CLAIM_RECEIPT_KIND : string=\"verifyhash.claim-receipt\"",
  "receipts.SCHEMA_VERSION : number=4",
  "receipts.buildAnchorReceipt : function/1",
  "receipts.buildReceipt : function/1",
  "receipts.diffManifest : function/2",
  "receipts.readReceipt : function/1",
  "receipts.writeReceipt : function/2",
  "recoverSigner : function/1",
  "seal : namespace",
  "seal.KIND : string=\"vh.evidence-seal\"",
  "seal.PacketSealError : function/1",
  "seal.SCHEMA_VERSION : number=1",
  "seal.TRUST_NOTE : string=\"This evidence seal is TAMPER-EVIDENT + OFFLINE-RECOMPUTABLE, NOT a trusted timestamp. Its Merkle `root` commits to the full set of (relPath, content) pairs in the directory: any edit, rename, add, or remove changes the root, and verify RE-DERIVES the root from the bytes you hold and LOCALIZES the change to the exact file (MATCH / CHANGED / MISSING / UNEXPECTED). It does NOT prove WHEN the sealing happened (\\\"sealed at T\\\" rides the human-owned signing/timestamp trust-root, STRATEGY.md P-3) and it is NOT a legal opinion. The packet is an UNTRUSTED transport container: verify never trusts the packet's own stored hashes.\"",
  "seal.buildSeal : function/1",
  "seal.readSeal : function/1",
  "seal.serializeSeal : function/1",
  "seal.validateSeal : function/1",
  "seal.verifySeal : function/2",
  "serializeSeal : function/1",
  "signSealWith : function/2",
  "signed : namespace",
  "signed.KIND : string=\"vh.evidence-seal-signed\"",
  "signed.TRUST_NOTE : string=\"A valid signature proves the HOLDER OF `signer`'s key vouched for THIS evidence seal (the embedded root + the full set of (relPath, content) pairs). It does NOT by itself prove a trustworthy TIMESTAMP: \\\"sealed/vouched since a date T\\\" still needs the human-owned signing/timestamp trust-root (needs-human, P-3). It is NOT a legal opinion. This evidence seal is TAMPER-EVIDENT + OFFLINE-RECOMPUTABLE, NOT a trusted timestamp. Its Merkle `root` commits to the full set of (relPath, content) pairs in the directory: any edit, rename, add, or remove changes the root, and verify RE-DERIVES the root from the bytes you hold and LOCALIZES the change to the exact file (MATCH / CHANGED / MISSING / UNEXPECTED). It does NOT prove WHEN the sealing happened (\\\"sealed at T\\\" rides the human-owned signing/timestamp trust-root, STRATEGY.md P-3) and it is NOT a legal opinion. The packet is an UNTRUSTED transport container: verify never trusts the packet's own stored hashes.\"",
  "signed.recoverSigner : function/1",
  "signed.signSealWith : function/2",
  "signed.validateSignedSeal : function/1",
  "signed.verifySignedAttestation : function/1",
  "signed.verifySignedSeal : function/1",
  "signed.verifySignedSealAttestation : function/1",
  "validateSeal : function/1",
  "validateSignedSeal : function/1",
  "verifySeal : function/2",
  "verifySignedAttestation : function/1",
  "verifySignedSeal : function/1",
  "verifySignedSealAttestation : function/1",
  "writeReceipt : function/2",
  "#verifySeal.result : accepted,changed,counts,matched,missing,recomputedRoot,rootMatches,sealedRoot,unexpected,verdict",
].join("\n");

describe("T-57.2 API contract: the public SDK ABI is pinned (semver guard) + doc/code drift guard", function () {
  const liveSurface = serializeSurface(api);

  // -------------------------------------------------------------------------
  // (A) THE SEMVER / ABI PIN.
  // -------------------------------------------------------------------------
  describe("(A) semver pin — the live index.js ABI byte-matches the frozen EXPECTED descriptor", function () {
    it("the live surface EQUALS the pin (any add/remove/rename/retype/arity/value change breaks it)", function () {
      // A single equality over the whole canonical block: the failure diff points at the drifted line.
      expect(liveSurface).to.equal(EXPECTED_SURFACE);
    });

    it("the pin is well-formed and non-empty (guards against an accidentally-blanked pin)", function () {
      expect(EXPECTED_SURFACE.length).to.be.greaterThan(0);
      // Every pinned line is a recognized descriptor line: a "path : abi" pair, or the verifySeal tail.
      // abi ∈ { namespace, function/<n>, string[="…"], number[=<n>], boolean[=<b>] } — the "=value" is
      // present for pinned wire values and absent for the value-exempt apiVersion (kind only).
      const lineRe =
        /^([A-Za-z][A-Za-z0-9]*(?:\.[A-Za-z][A-Za-z0-9_]*)?) : (namespace|function\/\d+|string(?:=.*)?|number(?:=-?\d+(?:\.\d+)?)?|boolean(?:=(?:true|false))?)$/;
      const tailRe = /^#verifySeal\.result : [a-zA-Z,]+$/;
      for (const line of EXPECTED_SURFACE.split("\n")) {
        const ok = lineRe.test(line) || tailRe.test(line);
        expect(ok, `malformed pin line: ${JSON.stringify(line)}`).to.equal(true);
      }
    });

    it("pins ABI dimensions a name-only guard would miss: an arity, a wire value, a result shape", function () {
      // Prove the pin actually carries these load-bearing dimensions (not just names + coarse kinds).
      expect(EXPECTED_SURFACE).to.include("verifySeal : function/2"); // arity
      expect(EXPECTED_SURFACE).to.include("buildSeal : function/1"); // arity
      expect(EXPECTED_SURFACE).to.include('seal.KIND : string="vh.evidence-seal"'); // frozen wire value
      expect(EXPECTED_SURFACE).to.include("seal.SCHEMA_VERSION : number=1"); // frozen wire value
      expect(EXPECTED_SURFACE).to.include(
        "#verifySeal.result : accepted,changed,counts,matched,missing,recomputedRoot,rootMatches,sealedRoot,unexpected,verdict"
      ); // result shape
    });
  });

  // -------------------------------------------------------------------------
  // NON-TRIVIALITY PROOF — the detector actually CATCHES drift; it isn't a tautology.
  // We build mutated copies of the live surface and assert serializeSurface(mutated) !== the live block,
  // i.e. the guard in (A) WOULD FAIL for each realistic breaking change — including the SILENT ones a
  // name-only guard misses (grown arity, bumped schema version, dropped result key).
  // -------------------------------------------------------------------------
  describe("the drift-detector is NON-TRIVIAL — a one-symbol change WOULD fail the pin", function () {
    // Deep-ish clone of the live surface we can mutate without touching the real (frozen) exports.
    function cloneSurface() {
      const copy = {};
      for (const k of Object.keys(api)) {
        const v = api[k];
        copy[k] = kindOf(v) === "namespace" ? { ...v } : v;
      }
      return copy;
    }

    // Line-exact membership: is `line` present as a WHOLE line (not a substring of another line,
    // e.g. `verifySeal : function/2` is the tail of `seal.verifySeal : function/2`).
    function hasLine(block, line) {
      return block.split("\n").includes(line);
    }

    it("baseline: serializeSurface of an unmutated clone MATCHES the live surface (control)", function () {
      expect(serializeSurface(cloneSurface())).to.equal(liveSurface);
    });

    it("ADDING an extra top-level key would FAIL the pin", function () {
      const mutated = cloneSurface();
      mutated.sneakyNewExport = function () {};
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(liveSurface);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "sneakyNewExport : function/0")).to.equal(true);
    });

    it("RENAMING a top-level key would FAIL the pin", function () {
      const mutated = cloneSurface();
      mutated.buildSealed = mutated.buildSeal; // typo/rename of buildSeal
      delete mutated.buildSeal;
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "buildSealed : function/1")).to.equal(true);
      // The top-level `buildSeal` line is gone (its namespace counterpart `seal.buildSeal` still exists).
      expect(hasLine(drifted, "buildSeal : function/1")).to.equal(false);
    });

    it("REMOVING a top-level key would FAIL the pin", function () {
      const mutated = cloneSurface();
      delete mutated.verifySeal;
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "verifySeal : function/2")).to.equal(false);
      expect(hasLine(drifted, "seal.verifySeal : function/2")).to.equal(true);
    });

    it("RETYPING a symbol (function -> string) would FAIL the pin", function () {
      const mutated = cloneSurface();
      mutated.verifySeal = "oops-now-a-string";
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, 'verifySeal : string="oops-now-a-string"')).to.equal(true);
      expect(hasLine(drifted, "verifySeal : function/2")).to.equal(false);
    });

    it("GROWING a function's ARITY (adding a required arg) would FAIL the pin — a name-only guard MISSES this", function () {
      const mutated = cloneSurface();
      // Same name, same kind (function), but now takes 3 args instead of 2 — a breaking call-signature change.
      mutated.verifySeal = function (seal, entries, opts) {
        return { seal, entries, opts };
      };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "verifySeal : function/3")).to.equal(true);
      expect(hasLine(drifted, "verifySeal : function/2")).to.equal(false);
    });

    it("BUMPING a frozen wire value (SCHEMA_VERSION 1 -> 2) would FAIL the pin — a name-only guard MISSES this", function () {
      const mutated = cloneSurface();
      mutated.seal = { ...mutated.seal, SCHEMA_VERSION: 2 };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "seal.SCHEMA_VERSION : number=2")).to.equal(true);
      expect(hasLine(drifted, "seal.SCHEMA_VERSION : number=1")).to.equal(false);
    });

    it("CHANGING a frozen KIND tag string would FAIL the pin — a name-only guard MISSES this", function () {
      const mutated = cloneSurface();
      mutated.seal = { ...mutated.seal, KIND: "vh.evidence-seal-v2" };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, 'seal.KIND : string="vh.evidence-seal-v2"')).to.equal(true);
      expect(hasLine(drifted, 'seal.KIND : string="vh.evidence-seal"')).to.equal(false);
    });

    it("ADDING / RENAMING a NAMESPACE MEMBER (nested drift) would FAIL the pin", function () {
      const added = cloneSurface();
      added.seal = { ...added.seal, extraSealMember: function () {} };
      const driftedAdd = serializeSurface(added);
      expect(driftedAdd).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(driftedAdd, "seal.extraSealMember : function/0")).to.equal(true);

      const renamed = cloneSurface();
      renamed.hashing = { ...renamed.hashing };
      renamed.hashing.hashBytez = renamed.hashing.hashBytes; // rename hashBytes -> hashBytez
      delete renamed.hashing.hashBytes;
      const driftedRename = serializeSurface(renamed);
      expect(driftedRename).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(driftedRename, "hashing.hashBytez : function/1")).to.equal(true);
      expect(hasLine(driftedRename, "hashing.hashBytes : function/1")).to.equal(false);
    });

    it("DROPPING a verifySeal RESULT KEY (verdict) would FAIL the pin — the behavioral tail catches it", function () {
      // The generator computes #verifySeal.result by actually calling verifySeal. Simulate a refactor that
      // stops returning `verdict`: feed serializeSurface a surface whose verifySeal omits that key.
      const mutated = cloneSurface();
      const realVerify = api.verifySeal;
      mutated.verifySeal = function (seal, entries) {
        const r = realVerify(seal, entries);
        const { verdict, ...rest } = r; // drop `verdict` from the returned object
        return rest;
      };
      mutated.seal = { ...mutated.seal, verifySeal: mutated.verifySeal };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      // The tail line no longer lists `verdict`.
      const tail = drifted.split("\n").find((l) => l.startsWith("#verifySeal.result : "));
      expect(tail, "verifySeal result tail present").to.be.a("string");
      expect(tail.includes("verdict")).to.equal(false);
    });

    // --- SIGNED-VERIFY SURFACE (T-58.2) — the pin CARRIES the signed symbols + arities, and the drift
    //     detector STILL fails on a fabricated extra / renamed key on that new surface. The signed path is
    //     the paid embed (EPIC-58); a silent add/rename/arity-change there must be as loud as anywhere else.

    it("the pin CARRIES the signed-verify symbols + their arities (a name-only guard would under-specify these)", function () {
      // The flat + namespaced signed-verify symbols, each with its pinned arity — the load-bearing ABI the
      // paid embed integrates against. If any of these silently changed, the pin must catch it.
      const signedLines = [
        "signSealWith : function/2",
        "validateSignedSeal : function/1",
        "verifySignedSeal : function/1",
        "verifySignedSealAttestation : function/1",
        "recoverSigner : function/1",
        "verifySignedAttestation : function/1",
        "signed : namespace",
        "signed.signSealWith : function/2",
        "signed.validateSignedSeal : function/1",
        "signed.verifySignedSeal : function/1",
        "signed.verifySignedSealAttestation : function/1",
        "signed.recoverSigner : function/1",
        "signed.verifySignedAttestation : function/1",
        'signed.KIND : string="vh.evidence-seal-signed"',
      ];
      for (const line of signedLines) {
        expect(EXPECTED_SURFACE, `pin is missing signed-verify line: ${line}`).to.include(line);
        expect(hasLine(EXPECTED_SURFACE, line), `pin line not present as a WHOLE line: ${line}`).to.equal(true);
      }
    });

    it("ADDING an extra `signed` namespace member (nested signed drift) WOULD FAIL the pin", function () {
      const mutated = cloneSurface();
      mutated.signed = { ...mutated.signed, sneakySignedExtra: function () {} };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(liveSurface);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "signed.sneakySignedExtra : function/0")).to.equal(true);
    });

    it("RENAMING a `signed` namespace member (verifySignedSeal -> verifySigned) WOULD FAIL the pin", function () {
      const mutated = cloneSurface();
      mutated.signed = { ...mutated.signed };
      mutated.signed.verifySigned = mutated.signed.verifySignedSeal; // typo/rename
      delete mutated.signed.verifySignedSeal;
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "signed.verifySigned : function/1")).to.equal(true);
      // The namespaced signed line is gone; the flat `verifySignedSeal` (a separate key) still exists.
      expect(hasLine(drifted, "signed.verifySignedSeal : function/1")).to.equal(false);
    });

    it("RENAMING a FLAT signed symbol (signSealWith -> signSeal) WOULD FAIL the pin", function () {
      const mutated = cloneSurface();
      mutated.signSeal = mutated.signSealWith; // rename the flat convenience export
      delete mutated.signSealWith;
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "signSeal : function/2")).to.equal(true);
      // The flat top-level `signSealWith` line is gone; the namespaced `signed.signSealWith` still exists.
      expect(hasLine(drifted, "signSealWith : function/2")).to.equal(false);
      expect(hasLine(drifted, "signed.signSealWith : function/2")).to.equal(true);
    });

    it("GROWING a signed function's ARITY (signSealWith 2 -> 3) WOULD FAIL the pin — a name-only guard MISSES this", function () {
      const mutated = cloneSurface();
      // Same name, same kind, but now a THIRD required arg — a breaking call-signature change on the paid path.
      const grown = function (seal, signer, opts) {
        return { seal, signer, opts };
      };
      mutated.signSealWith = grown;
      mutated.signed = { ...mutated.signed, signSealWith: grown };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "signSealWith : function/3")).to.equal(true);
      expect(hasLine(drifted, "signed.signSealWith : function/3")).to.equal(true);
      expect(hasLine(drifted, "signSealWith : function/2")).to.equal(false);
    });

    it("CHANGING the frozen signed-container KIND tag WOULD FAIL the pin — a name-only guard MISSES this", function () {
      const mutated = cloneSurface();
      mutated.signed = { ...mutated.signed, KIND: "vh.evidence-seal-signed-v2" };
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, 'signed.KIND : string="vh.evidence-seal-signed-v2"')).to.equal(true);
      expect(hasLine(drifted, 'signed.KIND : string="vh.evidence-seal-signed"')).to.equal(false);
    });

    it("REMOVING a flat signed symbol (verifySignedSeal) WOULD FAIL the pin", function () {
      const mutated = cloneSurface();
      delete mutated.verifySignedSeal;
      const drifted = serializeSurface(mutated);
      expect(drifted).to.not.equal(EXPECTED_SURFACE);
      expect(hasLine(drifted, "verifySignedSeal : function/1")).to.equal(false);
      // The namespaced counterpart is a distinct key and remains.
      expect(hasLine(drifted, "signed.verifySignedSeal : function/1")).to.equal(true);
    });

    it("does NOT trip on a benign VALUE change (apiVersion bump / bugfix inside a function body)", function () {
      // The version string is the ONE value intentionally allowed to move without a surface change: a
      // patch/minor release bumps apiVersion. To keep that from spuriously failing the pin, the descriptor
      // renders apiVersion by KIND only (never its value) — proven here.
      const mutated = cloneSurface();
      mutated.apiVersion = "9.9.9"; // a version bump — still a string, value not pinned
      expect(serializeSurface(mutated)).to.equal(liveSurface);
    });
  });

  // -------------------------------------------------------------------------
  // apiVersion is deliberately rendered by KIND only (value NOT pinned) so a release can bump it.
  // -------------------------------------------------------------------------
  it("apiVersion is pinned by KIND only, not value (so a version bump ships without a spurious failure)", function () {
    // The value-exemption lives in serializeSurface (not abiOf): the emitted line is the bare kind.
    const line = liveSurface.split("\n").find((l) => l.startsWith("apiVersion : "));
    expect(line, "apiVersion descriptor line present").to.be.a("string");
    expect(line).to.equal("apiVersion : string");
    // abiOf would pin the value (string="…") for any OTHER string — confirming the exemption is
    // deliberate and localized to apiVersion, not a property of abiOf itself.
    expect(abiOf(api.apiVersion)).to.equal(`string=${JSON.stringify(api.apiVersion)}`);
    expect(EXPECTED_SURFACE).to.include("apiVersion : string");
    expect(EXPECTED_SURFACE).to.not.include(`apiVersion : string="${api.apiVersion}"`);
  });

  // -------------------------------------------------------------------------
  // (C) SINGLE SOURCE OF TRUTH — the generator, the doc, and the pin all agree; `--check` is the CI gate.
  // -------------------------------------------------------------------------
  describe("(C) generator is the single source of truth — scripts/gen-sdk-surface.cjs", function () {
    it("the generator's computed surface EQUALS the live surface and the pin (one source, three consumers)", function () {
      const generated = gen.computeSurface();
      expect(generated).to.equal(liveSurface);
      expect(generated).to.equal(EXPECTED_SURFACE);
    });

    it("`--check` (checkDrift) reports NO drift on the committed tree — the CI drift gate is green", function () {
      const { ok, reasons } = gen.checkDrift();
      expect(ok, `drift reported: ${reasons.join("; ")}`).to.equal(true);
    });

    it("package.json wires an `sdk:surface` script so a maintainer regenerates with ONE command", function () {
      const pkg = require("../package.json");
      expect(pkg.scripts, "scripts block").to.be.an("object");
      expect(pkg.scripts["sdk:surface"], "sdk:surface script").to.be.a("string");
      expect(pkg.scripts["sdk:surface"]).to.include("gen-sdk-surface.cjs");
    });
  });

  // -------------------------------------------------------------------------
  // (B) DOC/CODE DRIFT — docs/SDK.md documents the surface and its symbol list byte-matches index.js.
  // -------------------------------------------------------------------------
  describe("(B) docs/SDK.md — documents every symbol + semver policy, byte-matched to index.js", function () {
    const sdkPath = path.join(ROOT, "docs", "SDK.md");
    const sdk = fs.readFileSync(sdkPath, "utf8");

    it("docs/SDK.md exists", function () {
      expect(fs.existsSync(sdkPath), "docs/SDK.md must exist").to.equal(true);
    });

    it("carries the generated surface block markers (from the generator, so they cannot drift)", function () {
      expect(sdk, "BEGIN marker missing").to.include(gen.MARKER);
      expect(sdk, "END marker missing").to.include(gen.END_MARKER);
    });

    it("the documented surface block BYTE-MATCHES the live index.js surface (no doc/code drift)", function () {
      const documented = gen.extractDocBlock(sdk);
      expect(documented, "a ```text fenced surface block between the markers").to.be.a("string");
      // Byte-for-byte identical to what index.js actually exports RIGHT NOW.
      expect(documented).to.equal(liveSurface);
      // And identical to the pin, transitively keeping doc == pin == code.
      expect(documented).to.equal(EXPECTED_SURFACE);
    });

    it("documents EVERY exported symbol by name in prose/table (not only in the code block)", function () {
      // Beyond the machine block, a human reading SDK.md must find each public symbol named.
      const begin = sdk.indexOf(gen.MARKER);
      const end = sdk.indexOf(gen.END_MARKER) + gen.END_MARKER.length;
      const prose = sdk.slice(0, begin) + sdk.slice(end);
      const names = new Set();
      for (const k of Object.keys(api)) {
        names.add(k);
        if (kindOf(api[k]) === "namespace") {
          for (const m of Object.keys(api[k])) names.add(m);
        }
      }
      for (const name of names) {
        expect(prose, `docs/SDK.md prose does not document symbol "${name}"`).to.include(name);
      }
    });

    it("documents EVERY new SIGNED-VERIFY symbol by name in the prose/table (T-58.2)", function () {
      // The signed-verify surface is the paid embed; SDK.md must NAME each new symbol in human prose (a
      // table/paragraph), not merely carry it in the machine block. Assert each appears OUTSIDE the block.
      const begin = sdk.indexOf(gen.MARKER);
      const end = sdk.indexOf(gen.END_MARKER) + gen.END_MARKER.length;
      const prose = sdk.slice(0, begin) + sdk.slice(end);
      const signedSymbols = [
        "signed",
        "signSealWith",
        "validateSignedSeal",
        "verifySignedSeal",
        "verifySignedSealAttestation",
        "recoverSigner",
        "verifySignedAttestation",
      ];
      for (const name of signedSymbols) {
        expect(prose, `docs/SDK.md prose does not document signed-verify symbol "${name}"`).to.include(name);
      }
      // The signed-container KIND tag is documented as the pinned wire value.
      expect(prose).to.include("vh.evidence-seal-signed");
      // The signed path's trust boundary is stated (a signature proves WHO vouched, not WHEN).
      expect(prose.toLowerCase()).to.match(/who vouched|vouched for/);
    });

    it("documents the SEMVER POLICY (major on breaking surface change; patch/minor safe)", function () {
      const lower = sdk.toLowerCase();
      expect(lower, "must mention semver").to.match(/semver|semantic version/);
      expect(lower, "must mention a major bump for breaking changes").to.match(/major/);
      // Names the breaking operations the pin catches.
      expect(lower).to.match(/remov|renam/);
      // States that apiVersion mirrors package.json.
      expect(sdk).to.include("apiVersion");
      expect(sdk).to.include("package.json");
    });

    it("documents that ARITY and frozen WIRE VALUES are part of the pinned contract", function () {
      const lower = sdk.toLowerCase();
      expect(lower, "must mention arity").to.match(/arity|parameter count|call signature/);
      expect(lower, "must mention the wire value / schema version being pinned").to.match(
        /wire value|schema version|kind tag/
      );
    });

    it("names the guarding test AND the generator so the doc points back at its enforcement", function () {
      expect(sdk).to.include("test/sdk.contract.test.js");
      expect(sdk).to.include("scripts/gen-sdk-surface.cjs");
    });

    it("states the deep cli/* internals are NOT part of the stable surface", function () {
      const lower = sdk.toLowerCase();
      expect(lower).to.match(/cli\/|internal/);
      expect(lower).to.match(/not (part of|guaranteed|stable)|no stability|unstable/);
    });
  });
});
