"use strict";

// test/trustledger.browser-core.test.js — T-65.1: the TrustLedger core is BROWSER-PORTABLE with
// ZERO behavior change.
//
// WHAT THIS SUITE PROVES (the four acceptance criteria):
//   (1) the vendored, zero-dependency pure-JS SHA-256 (trustledger/lib/sha256-vendored.js) is
//       byte-identical to Node's crypto.createHash("sha256") across published vectors, block-padding
//       edge lengths, hundreds of random buffers, non-ASCII/lone-surrogate UTF-8, EVERY committed
//       trustledger fixture file, and EVERY committed close artifact — a single mismatch fails;
//   (2) close.js's inputsDigest is BYTE-IDENTICAL to before the swap: the whole close artifact
//       rebuilt from the committed e2e fixtures equals the PINNED, pre-change fixture
//       (test/fixtures/trustledger-close-digests-pinned.json) byte for byte, and the digest inside
//       the committed prior-close.json (authored long before this change) is reproduced exactly;
//   (3) STATIC purity: walking the require graph from the browser-path modules (ingest, match,
//       reconcile, report, close, policy, sha256-vendored) reaches NO impure builtin require —
//       fs/path live ONLY in the isolated loader (trustledger/lib/policy-bundled-loader.js), which
//       policy.js requires LAZILY (never at module top level) and which nothing else references;
//   (4) DYNAMIC proof of (3): a child Node process BLOCKS every impure builtin at the module loader
//       and still loads the whole browser path and runs ingest -> buildPacket -> buildClose to the
//       same bytes — while the fs-backed bundledPolicies()/resolveState() seam throws, proving the
//       impurity sits behind exactly that one boundary.
//
// HONESTY: nothing here weakens an existing expectation — the suite only ADDS pins. The pinned
// close fixture was generated by the PRE-change implementation (node:crypto), so a digest drift of
// even one byte in the vendored path fails loudly.

const { expect } = require("chai");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execFileSync } = require("child_process");

const REPO = path.join(__dirname, "..");
const TL = path.join(REPO, "trustledger");
const VENDORED_PATH = path.join(TL, "lib", "sha256-vendored.js");
const LOADER_PATH = path.join(TL, "lib", "policy-bundled-loader.js");
const PINNED_PATH = path.join(__dirname, "fixtures", "trustledger-close-digests-pinned.json");

const vendored = require(VENDORED_PATH);
const { sha256, sha256Hex, sha256HexUtf8, utf8Bytes } = vendored;

const close = require("../trustledger/close");
const report = require("../trustledger/report");
const ingest = require("../trustledger/ingest");
const policyMod = require("../trustledger/policy");

// Node-crypto reference, lowercase hex — the oracle the vendored code must match byte-for-byte.
function refHex(bytesOrBuf) {
  return crypto.createHash("sha256").update(bytesOrBuf).digest("hex");
}
function refHexUtf8(str) {
  return crypto.createHash("sha256").update(str, "utf8").digest("hex");
}

// Recursively list every regular file under a directory (sorted, deterministic).
function walkFiles(dir) {
  const out = [];
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) out.push(...walkFiles(full));
    else if (st.isFile()) out.push(full);
  }
  return out;
}

// ---------------------------------------------------------------------------------------------
// The e2e close recipe — the SAME pipeline the CLI runs (ingest -> buildPacket -> buildClose),
// over the committed e2e fixtures, with the exact parameters the pinned fixture was generated
// with (pre-change). Rebuilding through the REAL pipeline (not hand-faked models) is what makes
// the byte-identity pin meaningful.
// ---------------------------------------------------------------------------------------------
const E2E = path.join(TL, "fixtures", "e2e");
const E2E_DATE = "2026-06-24";

function buildE2EClose(bankF, bookF, rentF, opts) {
  const bank = ingest.parseBankStatement(fs.readFileSync(path.join(E2E, bankF), "utf8"));
  const book = ingest.parseQuickBooksCSV(fs.readFileSync(path.join(E2E, bookF), "utf8"));
  const rentroll = ingest.parseRentRollCSV(fs.readFileSync(path.join(E2E, rentF), "utf8"));
  const model = report.buildPacket(
    Object.assign({ bank, book, rentroll, reportDate: E2E_DATE }, opts || {})
  );
  return close.buildClose(model);
}

// key in the pinned fixture -> how to rebuild it
const E2E_RECIPES = {
  clean: () => buildE2EClose("bank.csv", "quickbooks.csv", "rentroll.csv"),
  cleanWithPeriod: () =>
    buildE2EClose("bank.csv", "quickbooks.csv", "rentroll.csv", {
      period: "2026-06",
      opening: { bank: 0, book: 0 },
    }),
  nsf: () => buildE2EClose("bank.nsf.csv", "quickbooks.nsf.csv", "rentroll.nsf.csv"),
  short: () => buildE2EClose("bank.csv", "quickbooks.csv", "rentroll.short.csv"),
};

// ---------------------------------------------------------------------------------------------
// Static require-graph scanner. Comments are stripped first so prose mentioning require() can
// never mask or fake a dependency; every REMAINING `require` token must be a string-literal call
// we can classify. Relative requires are followed recursively.
// ---------------------------------------------------------------------------------------------
function stripComments(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
}

function requireSpecifiers(file) {
  const src = stripComments(fs.readFileSync(file, "utf8"));
  const specs = [];
  const re = /\brequire\s*\(/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    const rest = src.slice(m.index + m[0].length);
    const lit = rest.match(/^\s*["']([^"']+)["']\s*\)/);
    // A require whose argument is NOT a string literal would be a hole in this
    // static guarantee — forbid it outright on the scanned path.
    expect(lit, `${path.relative(REPO, file)} has a non-literal require()`).to.not.equal(null);
    specs.push(lit[1]);
  }
  return specs;
}

function resolveRelative(fromFile, spec) {
  const base = path.resolve(path.dirname(fromFile), spec);
  for (const cand of [base, `${base}.js`, path.join(base, "index.js")]) {
    if (fs.existsSync(cand) && fs.statSync(cand).isFile()) return cand;
  }
  throw new Error(`cannot resolve ${spec} from ${fromFile}`);
}

// Walk the require graph from `entries`; returns { files: Set<abs path>, builtins: Map<file, [spec]> }
// where builtins collects every NON-relative specifier seen, per file.
function walkRequireGraph(entries) {
  const files = new Set();
  const builtins = new Map();
  const queue = [...entries];
  while (queue.length > 0) {
    const file = queue.pop();
    if (files.has(file)) continue;
    files.add(file);
    for (const spec of requireSpecifiers(file)) {
      if (spec.startsWith(".")) {
        queue.push(resolveRelative(file, spec));
      } else {
        if (!builtins.has(file)) builtins.set(file, []);
        builtins.get(file).push(spec.replace(/^node:/, ""));
      }
    }
  }
  return { files, builtins };
}

// The browser-path entry modules (the ones the offline app must run), and the impure builtins
// that must be unreachable from them. `path` and `crypto` are deliberately INCLUDED: the whole
// point of T-65.1 is that the vendored SHA-256 removed `crypto` and the isolated loader removed
// `fs`/`path` from this path.
const BROWSER_ENTRIES = [
  path.join(TL, "ingest.js"),
  path.join(TL, "match.js"),
  path.join(TL, "reconcile.js"),
  path.join(TL, "report.js"),
  path.join(TL, "close.js"),
  path.join(TL, "policy.js"),
  VENDORED_PATH,
];
const IMPURE_BUILTINS = [
  "fs",
  "path",
  "os",
  "http",
  "https",
  "http2",
  "net",
  "tls",
  "dns",
  "dgram",
  "child_process",
  "cluster",
  "worker_threads",
  "crypto",
  "zlib",
  "readline",
  "repl",
  "vm",
  "v8",
  "inspector",
  "process",
];

describe("trustledger browser-portable core (T-65.1)", function () {
  // ============================================================================================
  // (1) vendored sha256 === node crypto
  // ============================================================================================
  describe("(1) vendored pure-JS sha256 is byte-identical to node crypto", function () {
    it("the vendored module source contains no require( and no import", function () {
      const src = fs.readFileSync(VENDORED_PATH, "utf8");
      expect(src, "vendored sha256 must not require() anything").to.not.match(/\brequire\s*\(/);
      expect(src, "vendored sha256 must not import anything").to.not.match(/^\s*import\s/m);
    });

    it("API shape: 32-byte Uint8Array digest, 64-char lowercase hex, TypeError on bad input", function () {
      const out = sha256(new Uint8Array([]));
      expect(out).to.be.instanceOf(Uint8Array);
      expect(out.length).to.equal(32);
      expect(sha256Hex(new Uint8Array([]))).to.match(/^[0-9a-f]{64}$/);
      expect(() => sha256("not bytes")).to.throw(TypeError);
      expect(() => sha256(123)).to.throw(TypeError);
      expect(() => sha256(null)).to.throw(TypeError);
      expect(() => sha256HexUtf8(42)).to.throw(TypeError);
      expect(() => utf8Bytes(42)).to.throw(TypeError);
    });

    it("matches the published FIPS 180-4 vectors exactly", function () {
      // Independently checkable constants (any SHA-256 reference reproduces these).
      expect(sha256Hex(new Uint8Array([]))).to.equal(
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
      );
      expect(sha256HexUtf8("abc")).to.equal(
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
      );
      expect(
        sha256HexUtf8("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")
      ).to.equal("248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1");
      expect(sha256HexUtf8("The quick brown fox jumps over the lazy dog")).to.equal(
        "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592"
      );
    });

    it("matches node crypto across every block/padding edge length", function () {
      // SHA-256 blocks are 64 bytes with the length field landing at 56 mod 64: 55/56/57 and the
      // multiples of 64 are exactly where padding bugs live.
      const lengths = [
        0, 1, 2, 3, 7, 8, 9, 31, 32, 33, 54, 55, 56, 57, 63, 64, 65, 118, 119, 120, 121, 127,
        128, 129, 255, 256, 1000, 4096, 65535,
      ];
      for (const len of lengths) {
        const buf = Buffer.alloc(len);
        for (let i = 0; i < len; i++) buf[i] = (i * 31 + len) & 0xff; // deterministic content
        expect(sha256Hex(buf), `len=${len}`).to.equal(refHex(buf));
      }
    });

    it("matches node crypto on >=500 random buffers of varied length", function () {
      for (let i = 0; i < 520; i++) {
        const len = i % 260; // 0..259 twice: covers multi-block and both padding branches
        const buf = crypto.randomBytes(len);
        expect(sha256Hex(buf), `random #${i} len=${len}`).to.equal(refHex(buf));
        expect(Buffer.from(sha256(buf)).toString("hex")).to.equal(refHex(buf));
      }
      // One large multi-KB buffer for good measure.
      const big = crypto.randomBytes(300 * 1024);
      expect(sha256Hex(big)).to.equal(refHex(big));
    });

    it("UTF-8 path: sha256HexUtf8 and utf8Bytes match Buffer.from(s, 'utf8') exactly (incl. lone surrogates)", function () {
      const strs = [
        "",
        "abc",
        "héllo wörld — «déjà vu»",
        "boundary: ߿ࠀ￿",
        "astral: 😀🚀\u{10FFFF}",
        "mixed 金額 ¥1,234 → €5,678",
        "\ud800", // lone high surrogate -> U+FFFD, exactly as Buffer.from/TextEncoder
        "a\udc00b", // lone low surrogate mid-string
        "pair then lone: 😀\ud83d!",
        "x".repeat(100000),
      ];
      for (const s of strs) {
        expect(
          Buffer.compare(Buffer.from(utf8Bytes(s)), Buffer.from(s, "utf8")),
          `utf8Bytes(${JSON.stringify(s.slice(0, 12))})`
        ).to.equal(0);
        expect(sha256HexUtf8(s), `sha256HexUtf8(${JSON.stringify(s.slice(0, 12))})`).to.equal(
          refHexUtf8(s)
        );
      }
    });

    it("matches node crypto over EVERY committed trustledger fixture file (the whole corpus)", function () {
      const files = walkFiles(path.join(TL, "fixtures"));
      // The walk must be real: the corpus ships CSVs, OFX, JSON policies, and close artifacts.
      expect(files.length).to.be.greaterThan(15);
      for (const f of files) {
        const bytes = fs.readFileSync(f);
        expect(sha256Hex(bytes), path.relative(REPO, f)).to.equal(refHex(bytes));
        // And via the string/UTF-8 door for the text fixtures, since that is the door close.js uses.
        const text = bytes.toString("utf8");
        expect(sha256HexUtf8(text), `${path.relative(REPO, f)} (utf8)`).to.equal(refHexUtf8(text));
      }
    });

    it("matches node crypto on the canonical close JSON of every committed close fixture and every e2e close", function () {
      // Every committed close artifact...
      const closes = walkFiles(path.join(TL, "fixtures")).filter((f) =>
        /close.*\.json$/.test(path.basename(f))
      );
      expect(closes.length, "at least one committed close fixture exists").to.be.greaterThan(0);
      // ...plus the four closes built through the REAL pipeline from the e2e fixtures.
      const artifacts = closes
        .map((f) => JSON.parse(fs.readFileSync(f, "utf8")))
        .concat(Object.values(E2E_RECIPES).map((build) => build()));
      for (const c of artifacts) {
        const canonical = JSON.stringify(c);
        expect(sha256HexUtf8(canonical)).to.equal(refHexUtf8(canonical));
      }
    });
  });

  // ============================================================================================
  // (2) inputsDigest byte-identity: pinned pre-change fixture
  // ============================================================================================
  describe("(2) close inputsDigest is byte-identical to the pre-change implementation", function () {
    it("rebuilding every e2e close reproduces the PINNED pre-change artifact byte-for-byte", function () {
      const pinned = JSON.parse(fs.readFileSync(PINNED_PATH, "utf8"));
      const keys = Object.keys(E2E_RECIPES);
      expect(Object.keys(pinned).sort()).to.eql(keys.slice().sort());
      for (const key of keys) {
        const rebuilt = E2E_RECIPES[key]();
        // Byte-identity of the WHOLE artifact (field order included), not just the digest.
        expect(JSON.stringify(rebuilt, null, 2), `e2e close "${key}"`).to.equal(
          JSON.stringify(pinned[key], null, 2)
        );
        expect(rebuilt.inputsDigest, `e2e close "${key}" digest`).to.equal(
          pinned[key].inputsDigest
        );
      }
    });

    it("the pinned digests are real SHA-256 values over the canonical projection (node-crypto recheck)", function () {
      const pinned = JSON.parse(fs.readFileSync(PINNED_PATH, "utf8"));
      for (const [key, c] of Object.entries(pinned)) {
        const canonical = JSON.stringify({
          schemaVersion: c.schemaVersion,
          period: c.period,
          reportDate: c.reportDate,
          opening: { bank: c.opening.bank, book: c.opening.book },
          ending: { bank: c.ending.bank, book: c.ending.book },
          subledger: c.subledger,
          tiesOut: c.tiesOut,
          pass: c.pass,
          inputs: {
            bankRecords: c.inputs.bankRecords,
            bookRecords: c.inputs.bookRecords,
            rentrollRecords: c.inputs.rentrollRecords,
          },
        });
        expect(refHexUtf8(canonical), `pinned "${key}"`).to.equal(c.inputsDigest);
      }
    });

    it("reproduces the digest inside the committed prior-close fixture (authored pre-change)", function () {
      const fix = JSON.parse(
        fs.readFileSync(path.join(TL, "fixtures", "corpus", "_shared", "prior-close.json"), "utf8")
      );
      const recomputed = close.digestInputs({
        period: fix.period,
        reportDate: fix.reportDate,
        opening: fix.opening,
        ending: fix.ending,
        subledger: fix.subledger,
        tiesOut: fix.tiesOut,
        pass: fix.pass,
        inputs: fix.inputs,
      });
      expect(recomputed).to.equal(fix.inputsDigest);
      // and the committed close still validates as-is
      expect(() => close.validateClose(fix)).to.not.throw();
    });
  });

  // ============================================================================================
  // (3) STATIC purity of the browser path
  // ============================================================================================
  describe("(3) static purity: no impure require reachable from the browser path", function () {
    it("walking the require graph reaches NO impure builtin outside the isolated loader", function () {
      const { files, builtins } = walkRequireGraph(BROWSER_ENTRIES);
      // The graph is real: it must include every entry plus the two lib modules.
      for (const entry of BROWSER_ENTRIES) expect(files.has(entry), entry).to.equal(true);
      expect(files.has(LOADER_PATH), "loader reached via policy.js").to.equal(true);

      for (const [file, specs] of builtins) {
        if (file === LOADER_PATH) {
          // The SOLE allowed exception: the isolated loader, and it may use ONLY fs+path.
          expect(specs.slice().sort()).to.eql(["fs", "path"]);
          continue;
        }
        // Everything else on the browser path requires NO bare/builtin module at all —
        // impure or otherwise.
        expect(
          specs,
          `${path.relative(REPO, file)} must not require bare/builtin modules (got: ${specs.join(", ")})`
        ).to.eql([]);
        for (const s of specs) {
          expect(IMPURE_BUILTINS, `${path.relative(REPO, file)} requires ${s}`).to.not.include(s);
        }
      }
    });

    it("the isolated loader is referenced ONLY by policy.js, and only lazily (never at top level)", function () {
      const { files } = walkRequireGraph(BROWSER_ENTRIES);
      for (const file of files) {
        if (file === LOADER_PATH) continue;
        const src = stripComments(fs.readFileSync(file, "utf8"));
        const mentions = /policy-bundled-loader/.test(src);
        if (file === path.join(TL, "policy.js")) {
          expect(mentions, "policy.js uses the loader").to.equal(true);
          // No TOP-LEVEL (column-0) binding of the loader: every use sits inside a function
          // body, so merely loading policy.js never executes the fs/path requires.
          expect(src).to.not.match(/^(const|let|var)\s[^\n]*policy-bundled-loader/m);
          expect(src).to.not.match(/^require\s*\(\s*["']\.\/lib\/policy-bundled-loader/m);
        } else {
          expect(mentions, `${path.relative(REPO, file)} must not touch the loader`).to.equal(
            false
          );
        }
      }
    });

    it("the vendored sha256 requires nothing; close.js requires the vendored module, not node crypto", function () {
      expect(requireSpecifiers(VENDORED_PATH)).to.eql([]);
      const closeSpecs = requireSpecifiers(path.join(TL, "close.js"));
      expect(closeSpecs).to.include("./lib/sha256-vendored");
      expect(closeSpecs).to.not.include("crypto");
      expect(closeSpecs).to.not.include("node:crypto");
    });
  });

  // ============================================================================================
  // (4) DYNAMIC proof: the browser path loads + runs with every impure builtin BLOCKED
  // ============================================================================================
  describe("(4) dynamic proof: the whole browser path runs with impure builtins blocked", function () {
    it("loads ingest/match/reconcile/report/close/policy and reproduces a pinned close with fs/path/crypto/net blocked; the loader seam alone throws", function () {
      // A tiny, fully inline reconciliation (no file reads inside the child).
      const bankCSV = "Date,Description,Amount\n2026-06-01,Rent deposit Unit 1,1500.00\n";
      const bookCSV = "Date,Memo,Amount\n2026-06-01,Rent deposit Unit 1,1500.00\n";
      const rentCSV = "Date,Unit,Tenant,Amount\n2026-06-01,Unit 1,Jones,1500.00\n";

      const script = `
        "use strict";
        const Module = require("module");
        const FORBIDDEN = new Set(${JSON.stringify(IMPURE_BUILTINS)});
        const origLoad = Module._load;
        Module._load = function (request) {
          const bare = String(request).replace(/^node:/, "");
          if (FORBIDDEN.has(bare)) {
            throw new Error("BLOCKED impure builtin on the browser path: " + request);
          }
          return origLoad.apply(this, arguments);
        };
        const TL = process.env.TL_DIR;
        // Loading every browser-path module must not touch a single blocked builtin.
        const ingest = require(TL + "/ingest.js");
        require(TL + "/match.js");
        require(TL + "/reconcile.js");
        const report = require(TL + "/report.js");
        const close = require(TL + "/close.js");
        const policy = require(TL + "/policy.js");
        require(TL + "/lib/sha256-vendored.js");

        // The pure policy functions work without fs.
        const p = policy.readPolicy({ schemaVersion: 1, state: "INLINE-TEST", severities: {} });
        const applied = policy.applyPolicy({ balances: {}, tiesOut: true, exceptions: [] }, p);
        if (applied.tiesOut !== true) throw new Error("applyPolicy broke");

        // The fs-backed seam — and ONLY that seam — is unavailable.
        let bundledThrew = false;
        try { policy.bundledPolicies(); } catch (e) { bundledThrew = true; }
        if (!bundledThrew) throw new Error("bundledPolicies() should hit the blocked loader");
        let resolveThrew = false;
        try { policy.resolveState("ca-example"); } catch (e) { resolveThrew = true; }
        if (!resolveThrew) throw new Error("resolveState() should hit the blocked loader");

        // The full pipeline runs: ingest -> buildPacket -> buildClose, all in-memory.
        const bank = ingest.parseBankStatement(${JSON.stringify(bankCSV)});
        const book = ingest.parseQuickBooksCSV(${JSON.stringify(bookCSV)});
        const rentroll = ingest.parseRentRollCSV(${JSON.stringify(rentCSV)});
        const model = report.buildPacket({
          bank, book, rentroll,
          reportDate: "2026-06-24",
          period: "2026-06",
          opening: { bank: 0, book: 0 },
        });
        const c = close.buildClose(model);
        process.stdout.write(JSON.stringify({ ok: true, close: c }));
      `;

      const out = execFileSync(process.execPath, ["-e", script], {
        env: Object.assign({}, process.env, { TL_DIR: TL }),
        encoding: "utf8",
      });
      const result = JSON.parse(out);
      expect(result.ok).to.equal(true);

      // The blocked-builtin close is byte-identical to the same close built HERE, in normal
      // Node (where close.js's digest byte-identity to node crypto is already pinned above).
      const bank = ingest.parseBankStatement(bankCSV);
      const book = ingest.parseQuickBooksCSV(bookCSV);
      const rentroll = ingest.parseRentRollCSV(rentCSV);
      const model = report.buildPacket({
        bank,
        book,
        rentroll,
        reportDate: "2026-06-24",
        period: "2026-06",
        opening: { bank: 0, book: 0 },
      });
      const expected = close.buildClose(model);
      expect(JSON.stringify(result.close)).to.equal(JSON.stringify(expected));
      // ...and its digest re-checks against node crypto directly.
      expect(result.close.inputsDigest).to.match(/^[0-9a-f]{64}$/);
    });

    it("in normal Node the lazy loader still serves the bundled policies unchanged", function () {
      // Zero behavior change on the Node side of the seam: same five fixtures, same resolution,
      // same BUNDLED_DIR value the module always exported.
      const all = policyMod.bundledPolicies();
      expect(all.map((e) => e.code)).to.eql([
        "ambiguous-deposit-example",
        "baseline",
        "ca-example",
        "negative-tenant-ledger-example",
        "owner-overdraw-example",
      ]);
      expect(policyMod.BUNDLED_DIR).to.equal(path.join(TL, "fixtures", "policy"));
      expect(Object.keys(policyMod)).to.include("BUNDLED_DIR");
      const byCode = policyMod.resolveState("baseline");
      expect(policyMod.resolveState(byCode.state).state).to.equal(byCode.state);
      expect(() => policyMod.resolveState("no-such-state")).to.throw(
        policyMod.PolicyError,
        /bundled states are:/
      );
    });
  });
});
