#!/usr/bin/env python3
"""og_card.py — the 1200x630 link-preview card, drawn from Python source only.

WHY THIS FILE EXISTS. LinkedIn, XING, Slack, Reddit, Discord and the
ActivityPub clients render a shared URL as a card. WITH an ``og:image`` that
card is a large picture tile; without one it is a narrow text strip worth a
fraction of the feed real-estate. ``gen_site.py`` already emits the full
Open Graph / Twitter tag block on every sitemapped page; the image was the last
missing piece, and the announce is one-shot.

THE CONSTRAINT that shapes everything here: ZERO new dependencies, no network,
no vendored font binary, and nothing that cannot be regenerated byte-for-byte
from source. So this module is a tiny renderer:

  * a STROKE FONT (:data:`GLYPHS`) — each glyph is a list of polylines in a
    normalised em box (baseline ``y=0``, cap height ``y=1``, x growing right).
    Curved letters are sampled from ellipse arcs by :func:`_arc` at import
    time, so ``O``/``S``/``e`` are real curves rather than staircases. This is
    hand-authored SOURCE, not a font file: it is diffable, and it is the reason
    a scaled 5x7 bitmap font (which turns to pixel mush at 100px cap height)
    was not used.
  * an ANTIALIASED rasteriser (:func:`draw_text`) — coverage of a pixel is
    ``clamp(halfwidth + 0.5 - distance_to_stroke, 0, 1)``, i.e. an analytic
    distance field with round caps and joins. Coverage is accumulated per text
    run with ``max()`` before compositing, so overlapping strokes inside one
    glyph (the crossbar of ``e``, the junction of ``h``) do not darken twice
    into a visible seam.
  * a PNG WRITER (:func:`encode_png`) — ``zlib`` + ``struct`` +
    ``binascii.crc32``, emitting exactly IHDR, IDAT, IEND. There is
    deliberately NO ``tIME`` and no ``tEXt`` chunk: those are the two chunks
    that would make the file differ between two runs, and the generator's
    staleness gate compares the committed bytes to a fresh render.

DETERMINISM. Every number below is a literal or is derived from the package's
own :func:`einvoice.capabilities`; there is no clock, no randomness, no
environment read, and no dict-ordering dependence (the glyph table is only ever
looked up by key). Two consecutive :func:`render_card` calls in any process on
any machine with the same zlib produce identical bytes.

HONEST LIMITS. This is a monoline geometric sans with a single weight, no
kerning pairs (only a uniform tracking value), no hinting and no bidi/complex
shaping. It renders the ASCII subset in :data:`GLYPHS` and raises
:class:`KeyError` on anything else — a loud build failure, because a card with
a silently dropped character is worse than a failed build. It is sized for one
job (a 1200x630 card at 26-120px cap height) and is not a general text engine.

    python3 og_card.py out.png    # render the card standalone, for eyeballing
"""

from __future__ import annotations

import binascii
import math
import struct
import zlib

# ---------------------------------------------------------------------------
# Geometry helper: an ellipse arc sampled as a polyline.
#
# ``a0``/``a1`` are degrees, x = cx + rx*cos(a), y = cy + ry*sin(a) (y grows
# UP, as everywhere in the em box). The sweep runs from a0 towards a1 in the
# direction implied by their order, at <= ``step`` degrees per sample, so a
# quarter turn is 15 samples: far below the point where the round-capped
# stroke would show facets at card size. The sample count is computed with
# ``math.ceil`` on a literal, so it is the same everywhere.


def _arc(cx, cy, rx, ry, a0, a1, step=6.0):
    """Polyline of (x, y) points along an ellipse arc, endpoints included."""
    span = a1 - a0
    n = max(2, int(math.ceil(abs(span) / step)) + 1)
    pts = []
    for i in range(n):
        a = math.radians(a0 + span * i / (n - 1))
        pts.append((cx + rx * math.cos(a), cy + ry * math.sin(a)))
    return pts


# ---------------------------------------------------------------------------
# THE STROKE FONT.
#
# GLYPHS[ch] = (advance_in_em, [polyline, ...]). Cap height is 1.0 em,
# x-height 0.70, ascender 1.0, descender -0.22 — the proportions of a
# geometric sans (Futura-ish single-story ``a``), chosen because monoline
# geometric shapes survive being drawn with one constant stroke width, which is
# all a distance-field renderer can do.
#
# A one-point polyline is not possible, so a dot (the tittle of ``i``, a full
# stop) is a zero-length-ish segment: the round cap turns it into a disc of the
# stroke's own diameter. That is deliberate and is why ``.`` reads at 30px.
GLYPHS = {
    " ": (0.30, []),
    # -- uppercase, body x in [0.07, 0.59] unless the letter is wide ---------
    "A": (0.66, [[(0.07, 0.0), (0.33, 1.0), (0.59, 0.0)],
                 [(0.155, 0.30), (0.505, 0.30)]]),
    "B": (0.66, [[(0.11, 0.0), (0.11, 1.0)],
                 [(0.11, 1.0), (0.30, 1.0)]
                 + _arc(0.30, 0.765, 0.21, 0.235, 90, -90)
                 + [(0.11, 0.53)],
                 [(0.11, 0.53), (0.31, 0.53)]
                 + _arc(0.31, 0.265, 0.24, 0.265, 90, -90)
                 + [(0.11, 0.0)]]),
    "C": (0.68, [_arc(0.35, 0.5, 0.26, 0.5, 55, 305)]),
    "D": (0.70, [[(0.11, 0.0), (0.11, 1.0)],
                 [(0.11, 1.0), (0.30, 1.0)]
                 + _arc(0.30, 0.5, 0.29, 0.5, 90, -90)
                 + [(0.11, 0.0)]]),
    "E": (0.62, [[(0.57, 1.0), (0.11, 1.0), (0.11, 0.0), (0.57, 0.0)],
                 [(0.11, 0.51), (0.50, 0.51)]]),
    "F": (0.60, [[(0.57, 1.0), (0.11, 1.0), (0.11, 0.0)],
                 [(0.11, 0.53), (0.50, 0.53)]]),
    "G": (0.72, [_arc(0.35, 0.5, 0.26, 0.5, 55, 330)
                 + [(0.61, 0.42), (0.42, 0.42)]]),
    "H": (0.70, [[(0.11, 0.0), (0.11, 1.0)], [(0.59, 0.0), (0.59, 1.0)],
                 [(0.11, 0.51), (0.59, 0.51)]]),
    "I": (0.30, [[(0.15, 0.0), (0.15, 1.0)]]),
    "J": (0.58, [[(0.50, 1.0), (0.50, 0.28)]
                 + _arc(0.28, 0.28, 0.22, 0.28, 0, -180)]),
    "K": (0.66, [[(0.11, 0.0), (0.11, 1.0)], [(0.57, 1.0), (0.20, 0.42)],
                 [(0.28, 0.55), (0.59, 0.0)]]),
    "L": (0.58, [[(0.11, 1.0), (0.11, 0.0), (0.55, 0.0)]]),
    "M": (0.80, [[(0.11, 0.0), (0.11, 1.0), (0.40, 0.28), (0.69, 1.0),
                  (0.69, 0.0)]]),
    "N": (0.70, [[(0.11, 0.0), (0.11, 1.0), (0.59, 0.0), (0.59, 1.0)]]),
    "O": (0.72, [_arc(0.36, 0.5, 0.29, 0.5, 0, 360)]),
    "P": (0.64, [[(0.11, 0.0), (0.11, 1.0)],
                 [(0.11, 1.0), (0.31, 1.0)]
                 + _arc(0.31, 0.75, 0.23, 0.25, 90, -90)
                 + [(0.11, 0.50)]]),
    "Q": (0.72, [_arc(0.36, 0.5, 0.29, 0.5, 0, 360),
                 [(0.44, 0.22), (0.66, -0.06)]]),
    "R": (0.66, [[(0.11, 0.0), (0.11, 1.0)],
                 [(0.11, 1.0), (0.31, 1.0)]
                 + _arc(0.31, 0.75, 0.23, 0.25, 90, -90)
                 + [(0.11, 0.50)],
                 [(0.30, 0.50), (0.59, 0.0)]]),
    "S": (0.64, [_arc(0.33, 0.745, 0.235, 0.245, 20, 250)
                 + _arc(0.33, 0.255, 0.235, 0.245, 70, -160)]),
    "T": (0.62, [[(0.05, 1.0), (0.57, 1.0)], [(0.31, 1.0), (0.31, 0.0)]]),
    "U": (0.70, [[(0.11, 1.0), (0.11, 0.28)]
                 + _arc(0.35, 0.28, 0.24, 0.28, 180, 360)
                 + [(0.59, 1.0)]]),
    "V": (0.66, [[(0.07, 1.0), (0.33, 0.0), (0.59, 1.0)]]),
    "W": (0.94, [[(0.06, 1.0), (0.26, 0.0), (0.47, 0.72), (0.68, 0.0),
                  (0.88, 1.0)]]),
    "X": (0.66, [[(0.09, 1.0), (0.57, 0.0)], [(0.57, 1.0), (0.09, 0.0)]]),
    "Y": (0.66, [[(0.09, 1.0), (0.33, 0.52), (0.57, 1.0)],
                 [(0.33, 0.52), (0.33, 0.0)]]),
    "Z": (0.64, [[(0.09, 1.0), (0.57, 1.0), (0.09, 0.0), (0.57, 0.0)]]),
    # -- digits, all the same 0.62 advance so numbers line up ---------------
    "0": (0.62, [_arc(0.31, 0.5, 0.24, 0.5, 0, 360)]),
    "1": (0.62, [[(0.13, 0.80), (0.31, 1.0), (0.31, 0.0)]]),
    "2": (0.62, [_arc(0.31, 0.745, 0.24, 0.245, 200, -20)
                 + [(0.07, 0.0), (0.56, 0.0)]]),
    "3": (0.62, [_arc(0.31, 0.75, 0.235, 0.25, 195, -60)
                 + _arc(0.31, 0.26, 0.245, 0.26, 60, -195)]),
    "4": (0.62, [[(0.44, 0.0), (0.44, 1.0), (0.06, 0.30), (0.57, 0.30)]]),
    "5": (0.62, [[(0.53, 1.0), (0.17, 1.0), (0.14, 0.60)]
                 + _arc(0.31, 0.30, 0.245, 0.30, 95, -165)]),
    "6": (0.62, [_arc(0.31, 0.30, 0.245, 0.30, 90, -270),
                 _arc(0.31, 0.30, 0.245, 0.64, 180, 65)]),
    "7": (0.62, [[(0.07, 1.0), (0.55, 1.0), (0.22, 0.0)]]),
    "8": (0.62, [_arc(0.31, 0.755, 0.215, 0.245, 0, 360),
                 _arc(0.31, 0.255, 0.245, 0.255, 0, 360)]),
    "9": (0.62, [_arc(0.31, 0.70, 0.245, 0.30, 0, 360),
                 _arc(0.31, 0.70, 0.245, 0.64, 0, -115)]),
    # -- lowercase, x-height 0.70 -------------------------------------------
    "a": (0.64, [_arc(0.29, 0.35, 0.225, 0.35, 0, 360),
                 [(0.515, 0.70), (0.515, 0.0)]]),
    "b": (0.64, [_arc(0.33, 0.35, 0.225, 0.35, 0, 360),
                 [(0.105, 1.0), (0.105, 0.0)]]),
    "c": (0.60, [_arc(0.32, 0.35, 0.235, 0.35, 50, 310)]),
    "d": (0.64, [_arc(0.30, 0.35, 0.225, 0.35, 0, 360),
                 [(0.525, 1.0), (0.525, 0.0)]]),
    "e": (0.62, [[(0.545, 0.35)] + _arc(0.31, 0.35, 0.235, 0.35, 0, 310),
                 [(0.085, 0.35), (0.545, 0.35)]]),
    "f": (0.40, [[(0.10, 0.0), (0.10, 0.80)]
                 + _arc(0.28, 0.80, 0.18, 0.20, 180, 90),
                 [(0.02, 0.68), (0.40, 0.68)]]),
    "g": (0.64, [_arc(0.31, 0.35, 0.235, 0.35, 0, 360),
                 [(0.545, 0.70), (0.545, -0.02)]
                 + _arc(0.33, -0.02, 0.215, 0.20, 0, -180)]),
    "h": (0.62, [[(0.10, 0.0), (0.10, 1.0)],
                 [(0.10, 0.45)] + _arc(0.31, 0.45, 0.21, 0.25, 180, 0)
                 + [(0.52, 0.0)]]),
    "i": (0.28, [[(0.14, 0.70), (0.14, 0.0)],
                 [(0.14, 0.90), (0.14, 0.905)]]),
    "j": (0.28, [[(0.14, 0.70), (0.14, 0.0)]
                 + _arc(-0.04, 0.0, 0.18, 0.18, 0, -90),
                 [(0.14, 0.90), (0.14, 0.905)]]),
    "k": (0.58, [[(0.10, 0.0), (0.10, 1.0)], [(0.52, 0.70), (0.16, 0.30)],
                 [(0.26, 0.40), (0.54, 0.0)]]),
    "l": (0.26, [[(0.13, 1.0), (0.13, 0.0)]]),
    "m": (0.94, [[(0.10, 0.0), (0.10, 0.70)],
                 [(0.10, 0.47)] + _arc(0.28, 0.47, 0.18, 0.23, 180, 0)
                 + [(0.46, 0.0)],
                 [(0.46, 0.47)] + _arc(0.64, 0.47, 0.18, 0.23, 180, 0)
                 + [(0.82, 0.0)]]),
    "n": (0.62, [[(0.10, 0.0), (0.10, 0.70)],
                 [(0.10, 0.45)] + _arc(0.31, 0.45, 0.21, 0.25, 180, 0)
                 + [(0.52, 0.0)]]),
    "o": (0.64, [_arc(0.32, 0.35, 0.245, 0.35, 0, 360)]),
    "p": (0.64, [_arc(0.33, 0.35, 0.225, 0.35, 0, 360),
                 [(0.105, 0.70), (0.105, -0.22)]]),
    "q": (0.64, [_arc(0.30, 0.35, 0.225, 0.35, 0, 360),
                 [(0.525, 0.70), (0.525, -0.22)]]),
    "r": (0.44, [[(0.10, 0.0), (0.10, 0.70)],
                 [(0.10, 0.42)] + _arc(0.30, 0.42, 0.20, 0.28, 180, 70)]),
    "s": (0.54, [_arc(0.28, 0.525, 0.195, 0.175, 20, 250)
                 + _arc(0.28, 0.175, 0.195, 0.175, 70, -160)]),
    "t": (0.46, [[(0.24, 1.0), (0.24, 0.16)]
                 + _arc(0.40, 0.16, 0.16, 0.16, 180, 270),
                 [(0.03, 0.70), (0.45, 0.70)]]),
    "u": (0.62, [[(0.10, 0.70), (0.10, 0.25)]
                 + _arc(0.31, 0.25, 0.21, 0.25, 180, 360)
                 + [(0.52, 0.70)]]),
    "v": (0.58, [[(0.05, 0.70), (0.29, 0.0), (0.53, 0.70)]]),
    "w": (0.86, [[(0.04, 0.70), (0.23, 0.0), (0.43, 0.52), (0.63, 0.0),
                  (0.82, 0.70)]]),
    "x": (0.56, [[(0.06, 0.70), (0.50, 0.0)], [(0.50, 0.70), (0.06, 0.0)]]),
    "y": (0.58, [[(0.05, 0.70), (0.31, 0.06)],
                 [(0.53, 0.70), (0.20, -0.22)]]),
    "z": (0.54, [[(0.07, 0.70), (0.47, 0.70), (0.07, 0.0), (0.47, 0.0)]]),
    # -- punctuation --------------------------------------------------------
    "/": (0.46, [[(0.05, -0.06), (0.41, 1.02)]]),
    "-": (0.42, [[(0.08, 0.40), (0.34, 0.40)]]),
    ".": (0.28, [[(0.14, 0.0), (0.14, 0.005)]]),
    ",": (0.28, [[(0.16, 0.03), (0.09, -0.15)]]),
    ":": (0.28, [[(0.14, 0.0), (0.14, 0.005)],
                 [(0.14, 0.48), (0.14, 0.485)]]),
    "+": (0.58, [[(0.09, 0.40), (0.49, 0.40)], [(0.29, 0.20), (0.29, 0.60)]]),
    "(": (0.36, [_arc(0.52, 0.40, 0.46, 0.72, 150, 210)]),
    ")": (0.36, [_arc(-0.16, 0.40, 0.46, 0.72, 30, -30)]),
    # U+00B7 MIDDLE DOT, written as an escape so this file stays pure ASCII.
    "\u00b7": (0.34, [[(0.17, 0.34), (0.17, 0.345)]]),
}

# Stroke width as a fraction of cap height. 0.105 is the value that stayed
# legible when the card was rendered and inspected at 26px cap (the eyebrow
# line): thinner strokes vanished into the dark background, thicker ones closed
# up the counters of ``e`` and ``a``.
STROKE_EM = 0.105


def text_width(text, size, tracking=0.0):
    """Advance width in pixels of ``text`` at cap height ``size``.

    ``tracking`` is extra letter spacing in em, applied BETWEEN glyphs (not
    after the last one), so a centred or right-aligned run measures correctly.
    """
    if not text:
        return 0.0
    total = sum(GLYPHS[ch][0] for ch in text)
    return (total + tracking * (len(text) - 1)) * size


class Canvas:
    """An RGB8 raster with a flat background colour, composited in place."""

    def __init__(self, width, height, background):
        self.width = width
        self.height = height
        self.buf = bytearray(bytes(background) * (width * height))

    def fill_rect(self, x, y, w, h, color):
        """Opaque axis-aligned rectangle (used for the accent rules)."""
        x0, y0 = max(0, int(x)), max(0, int(y))
        x1 = min(self.width, int(x + w))
        y1 = min(self.height, int(y + h))
        row = bytes(color) * max(0, x1 - x0)
        for py in range(y0, y1):
            off = (py * self.width + x0) * 3
            self.buf[off:off + len(row)] = row

    def composite(self, coverage, color):
        """Blend ``color`` into the raster at the given {index: alpha} map."""
        buf = self.buf
        cr, cg, cb = color
        for idx, a in coverage.items():
            if a <= 0.0:
                continue
            if a > 1.0:
                a = 1.0
            o = idx * 3
            buf[o] = int(buf[o] + (cr - buf[o]) * a + 0.5)
            buf[o + 1] = int(buf[o + 1] + (cg - buf[o + 1]) * a + 0.5)
            buf[o + 2] = int(buf[o + 2] + (cb - buf[o + 2]) * a + 0.5)


def _stroke(coverage, width, height, x1, y1, x2, y2, half):
    """Accumulate round-capped-segment coverage into ``coverage`` (max-blend).

    Coverage of a pixel centre is ``half + 0.5 - distance``, clamped to [0, 1]:
    a one-pixel-wide analytic ramp at the stroke edge, which is what makes the
    curves read as curves instead of stairs. Only the segment's bounding box
    (grown by ``half + 1``) is visited, so cost is proportional to inked area.
    """
    pad = half + 1.0
    lo_x = max(0, int(math.floor(min(x1, x2) - pad)))
    hi_x = min(width - 1, int(math.ceil(max(x1, x2) + pad)))
    lo_y = max(0, int(math.floor(min(y1, y2) - pad)))
    hi_y = min(height - 1, int(math.ceil(max(y1, y2) + pad)))
    if lo_x > hi_x or lo_y > hi_y:
        return
    dx = x2 - x1
    dy = y2 - y1
    dd = dx * dx + dy * dy
    edge = half + 0.5
    for py in range(lo_y, hi_y + 1):
        fy = py + 0.5 - y1
        base = py * width
        for px in range(lo_x, hi_x + 1):
            fx = px + 0.5 - x1
            if dd > 0.0:
                t = (fx * dx + fy * dy) / dd
                if t < 0.0:
                    t = 0.0
                elif t > 1.0:
                    t = 1.0
            else:
                t = 0.0
            ox = fx - t * dx
            oy = fy - t * dy
            a = edge - math.sqrt(ox * ox + oy * oy)
            if a <= 0.0:
                continue
            if a > 1.0:
                a = 1.0
            idx = base + px
            if a > coverage.get(idx, 0.0):
                coverage[idx] = a


def draw_text(canvas, text, x, baseline, size, color, tracking=0.0):
    """Draw ``text`` with its cap height at ``size`` px, left edge at ``x``.

    ``baseline`` is the device y of the em box's ``y=0`` line (y grows DOWN on
    the canvas, UP in the em box, hence the sign flip). Returns the pen x after
    the run. Raises ``KeyError`` on a character with no glyph.
    """
    half = STROKE_EM * size / 2.0
    coverage = {}
    pen = float(x)
    for i, ch in enumerate(text):
        advance, paths = GLYPHS[ch]
        for path in paths:
            prev = None
            for (gx, gy) in path:
                cur = (pen + gx * size, baseline - gy * size)
                if prev is not None:
                    _stroke(coverage, canvas.width, canvas.height,
                            prev[0], prev[1], cur[0], cur[1], half)
                prev = cur
        pen += advance * size
        if i != len(text) - 1:
            pen += tracking * size
    canvas.composite(coverage, color)
    return pen


# ---------------------------------------------------------------------------
# PNG encoding. Colour type 2 (truecolour, 8 bit), one IDAT, no ancillary
# chunks. Filters are chosen per scanline by the standard minimum-sum-of-
# absolute-differences heuristic over the five filter types, which is a pure
# function of the pixel data — same input, same filter choices, same bytes.

def _paeth(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def _filter_scanline(cur, prev, bpp):
    """(filter_type, filtered_bytes) for one scanline, best of the five."""
    n = len(cur)
    cands = []
    # 0 None
    cands.append((0, bytes(cur)))
    # 1 Sub
    sub = bytearray(n)
    for i in range(n):
        left = cur[i - bpp] if i >= bpp else 0
        sub[i] = (cur[i] - left) & 0xFF
    cands.append((1, bytes(sub)))
    # 2 Up
    up = bytearray(n)
    for i in range(n):
        up[i] = (cur[i] - prev[i]) & 0xFF
    cands.append((2, bytes(up)))
    # 3 Average
    avg = bytearray(n)
    for i in range(n):
        left = cur[i - bpp] if i >= bpp else 0
        avg[i] = (cur[i] - ((left + prev[i]) >> 1)) & 0xFF
    cands.append((3, bytes(avg)))
    # 4 Paeth
    pae = bytearray(n)
    for i in range(n):
        left = cur[i - bpp] if i >= bpp else 0
        ul = prev[i - bpp] if i >= bpp else 0
        pae[i] = (cur[i] - _paeth(left, prev[i], ul)) & 0xFF
    cands.append((4, bytes(pae)))
    best = None
    best_score = None
    for ftype, data in cands:
        # Signed-magnitude sum: bytes are treated as -128..127, the heuristic
        # the PNG spec itself recommends.
        score = sum(b if b < 128 else 256 - b for b in data)
        if best_score is None or score < best_score:
            best_score = score
            best = (ftype, data)
    return best


def _chunk(tag, payload):
    return (struct.pack(">I", len(payload)) + tag + payload
            + struct.pack(">I", binascii.crc32(tag + payload) & 0xFFFFFFFF))


def encode_png(width, height, rgb):
    """RGB8 pixel bytes -> a complete PNG file as ``bytes``.

    Exactly three chunks: IHDR, IDAT, IEND. No ``tIME``, no ``tEXt``, no
    ``pHYs`` — nothing that varies between runs.
    """
    if len(rgb) != width * height * 3:
        raise ValueError("pixel buffer is %d bytes, expected %d"
                         % (len(rgb), width * height * 3))
    bpp = 3
    stride = width * bpp
    raw = bytearray()
    prev = bytes(stride)
    for y in range(height):
        cur = rgb[y * stride:(y + 1) * stride]
        ftype, data = _filter_scanline(cur, prev, bpp)
        raw.append(ftype)
        raw += data
        prev = cur
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n"
            + _chunk(b"IHDR", ihdr)
            + _chunk(b"IDAT", zlib.compress(bytes(raw), 9))
            + _chunk(b"IEND", b""))


# ---------------------------------------------------------------------------
# THE CARD ITSELF.
#
# 1200x630 is the size LinkedIn, X and Facebook all crop to (1.91:1); at that
# ratio nothing is trimmed on any of them. Colours are the SAME hexes the
# generated pages already use, so the card cannot look like a different
# product: #161b22 surface, #e6edf3 primary text, #8b949e muted, #4493f8
# accent.
CARD_WIDTH = 1200
CARD_HEIGHT = 630
_BG = (0x16, 0x1B, 0x22)
_FG = (0xE6, 0xED, 0xF3)
_MUTED = (0x8B, 0x94, 0x9E)
_ACCENT = (0x44, 0x93, 0xF8)


def render_card(title, standard, facts, source):
    """The card bytes.

    Every string is passed IN by the caller (``gen_site.py``), which reads
    them from the package's own :func:`einvoice.capabilities` and its BASE_URL
    constant — this module invents no fact and hard-codes no number.

    :param title: the product name, big.
    :param standard: the conformance line, e.g. the standards this checks.
    :param facts: the derived figures line (rule count, engine version).
    :param source: the site the card belongs to, as an eyebrow.
    """
    for name, value in (("title", title), ("standard", standard),
                        ("facts", facts), ("source", source)):
        if not value or not value.strip():
            raise ValueError("card %s is empty" % name)
    c = Canvas(CARD_WIDTH, CARD_HEIGHT, _BG)
    # A 10px accent band down the left edge: the one purely decorative
    # element, and the thing that makes the tile recognisable in a feed.
    c.fill_rect(0, 0, 10, CARD_HEIGHT, _ACCENT)

    margin = 96
    draw_text(c, source, margin, 168, 25, _MUTED, tracking=0.09)
    draw_text(c, title, margin, 320, 116, _FG)
    draw_text(c, standard, margin, 410, 44, _FG, tracking=0.005)
    c.fill_rect(margin, 456, 132, 5, _ACCENT)
    draw_text(c, facts, margin, 536, 31, _MUTED, tracking=0.02)
    return encode_png(CARD_WIDTH, CARD_HEIGHT, bytes(c.buf))


if __name__ == "__main__":  # pragma: no cover - manual eyeballing only
    # A LAYOUT preview, not the shipped card: the facts line is deliberately
    # written as placeholders rather than real figures, because the only place
    # allowed to state a rule count or a version is gen_site.py, which reads
    # both from einvoice.capabilities(). Run `python3 gen_site.py` to produce
    # the real www/og-card.png.
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "og-card-preview.png"
    with open(out, "wb") as fh:
        fh.write(render_card("einvoice", "EN 16931 / XRechnung conformance",
                             "(rule count) business rules . engine (version)",
                             "verifyhash.com/einvoice"))
    print("wrote %s (layout preview)" % out)
