#!/usr/bin/env python3
"""Independently verify the committed conformance-claim attestation.

A skeptical evaluator runs this to confirm, from the source tree alone, that
``attestation.json`` still reflects reality -- i.e. that nobody has quietly
edited a rule count, a coverage number, a test-suite pass rate, or a pinned
corpus hash since the attestation was published. Two independent checks:

  1. RECOMPUTE-AND-COMPARE. Regenerate the attestation FRESH from the four live
     source artifacts (export/rules.json, export/coverage.json,
     testsuite_conformance.json, sbom/bom.json) and assert it is BYTE-IDENTICAL
     to the committed attestation.json. Any drift in a recorded number changes
     the regenerated bytes (and the content hash), so this fails closed.

  2. CORPUS-BYTES BINDING. Re-walk each vendored corpus tree with gen_sbom's
     own ``corpus_sha256`` and assert the digest still equals the SHA-256
     recorded in the attestation. This binds the attestation to the actual
     bytes on disk -- editing a corpus file (without also regenerating the
     SBOM) is caught here even though check 1 alone would not see it.

Exits 0 iff both checks pass; non-zero (with a diagnostic on stderr) on ANY
drift. Standard library only.
"""

from __future__ import annotations

import sys
from pathlib import Path

import gen_attestation
import gen_sbom

HERE = Path(__file__).resolve().parent
ATTESTATION_PATH = HERE / "attestation.json"


def _fail(msg):
    sys.stderr.write("attestation verify FAILED: " + msg + "\n")
    return 1


def verify():
    """Return 0 if the committed attestation verifies, non-zero otherwise."""
    if not ATTESTATION_PATH.is_file():
        return _fail("attestation.json is missing at %s" % ATTESTATION_PATH)

    committed = ATTESTATION_PATH.read_text(encoding="utf-8")

    # --- Check 1: recompute from live source artifacts, byte-compare. --------
    try:
        recomputed = gen_attestation.attestation_json()
    except SystemExit as exc:
        return _fail("regeneration aborted: %s" % exc)
    if recomputed != committed:
        return _fail(
            "recomputed attestation differs from the committed "
            "attestation.json -- a rule count, coverage number, pass rate, or "
            "recorded corpus sha has drifted (or the file was hand-edited)."
        )

    # --- Check 2: re-walk the live corpus tree, confirm pinned shas. ---------
    doc = gen_attestation.json.loads(committed)
    corpus = doc["attestation"]["corpus"]
    for entry in corpus:
        # entry["path"] is repo-relative like "corpus/cen-en16931"; the tree
        # lives under gen_sbom.CORPUS_ROOT (== HERE/"corpus").
        rel = entry["path"]
        prefix = "corpus/"
        if not rel.startswith(prefix):
            return _fail("unexpected corpus path %r in attestation" % rel)
        root = gen_sbom.CORPUS_ROOT / rel[len(prefix):]
        if not root.is_dir():
            return _fail("vendored corpus tree is missing: %s" % root)
        live = gen_sbom.corpus_sha256(root)
        if live != entry["sha256"]:
            return _fail(
                "corpus %r content hash drifted: attestation pins %s but the "
                "on-disk tree hashes to %s"
                % (entry["name"], entry["sha256"], live)
            )

    sys.stdout.write(
        "attestation verify OK: %d rules, %d corpus artifacts, "
        "content_sha256=%s\n"
        % (
            doc["attestation"]["rules"]["count"],
            len(corpus),
            doc["content_sha256"],
        )
    )
    return 0


def main(argv=None):
    return verify()


if __name__ == "__main__":
    raise SystemExit(main())
